FROM postgres:14

ARG USER_ID
ARG GROUP_ID

RUN mkdir /data

RUN groupadd -g $GROUP_ID group_user && useradd -rm -d /home/user -s /bin/bash -g group_user -G sudo -u $USER_ID user
RUN chown -R user:group_user /data

USER user